export interface TimezoneOption {
  value: string;
  label: string;
}

export const timezones: TimezoneOption[] = [
  { value: "America/Mexico_City", label: "Ciudad de Mexico" },
  { value: "America/New_York", label: "Nueva York" },
  { value: "America/Chicago", label: "Chicago" },
  { value: "America/Denver", label: "Denver" },
  { value: "America/Los_Angeles", label: "Los Angeles" },
  { value: "America/Phoenix", label: "Phoenix" },
  { value: "America/Anchorage", label: "Anchorage" },
  { value: "America/Honolulu", label: "Honolulu" },
  { value: "America/Toronto", label: "Toronto" },
  { value: "America/Vancouver", label: "Vancouver" },
  { value: "America/Montreal", label: "Montreal" },
  { value: "America/Argentina/Buenos_Aires", label: "Buenos Aires" },
  { value: "America/Sao_Paulo", label: "Sao Paulo" },
  { value: "America/Santiago", label: "Santiago" },
  { value: "America/Bogota", label: "Bogota" },
  { value: "America/Lima", label: "Lima" },
  { value: "America/Caracas", label: "Caracas" },
  { value: "America/Montevideo", label: "Montevideo" },
  { value: "America/La_Paz", label: "La Paz" },
  { value: "America/Asuncion", label: "Asuncion" },
  { value: "America/Guayaquil", label: "Guayaquil" },
  { value: "America/Guatemala", label: "Guatemala" },
  { value: "America/Tegucigalpa", label: "Tegucigalpa" },
  { value: "America/Managua", label: "Managua" },
  { value: "America/San_Jose", label: "San Jose" },
  { value: "America/Panama", label: "Panama" },
  { value: "America/Havana", label: "Havana" },
  { value: "America/Santo_Domingo", label: "Santo Domingo" },
  { value: "America/San_Juan", label: "San Juan" },
  { value: "America/El_Salvador", label: "El Salvador" },
  { value: "Europe/London", label: "Londres" },
  { value: "Europe/Paris", label: "Paris" },
  { value: "Europe/Berlin", label: "Berlin" },
  { value: "Europe/Madrid", label: "Madrid" },
  { value: "Europe/Rome", label: "Roma" },
  { value: "Europe/Amsterdam", label: "Amsterdam" },
  { value: "Europe/Brussels", label: "Bruselas" },
  { value: "Europe/Vienna", label: "Viena" },
  { value: "Europe/Zurich", label: "Zurich" },
  { value: "Europe/Stockholm", label: "Estocolmo" },
  { value: "Europe/Oslo", label: "Oslo" },
  { value: "Europe/Copenhagen", label: "Copenhague" },
  { value: "Europe/Helsinki", label: "Helsinki" },
  { value: "Europe/Warsaw", label: "Varsovia" },
  { value: "Europe/Prague", label: "Praga" },
  { value: "Europe/Budapest", label: "Budapest" },
  { value: "Europe/Athens", label: "Atenas" },
  { value: "Europe/Lisbon", label: "Lisboa" },
  { value: "Europe/Dublin", label: "Dublin" },
  { value: "Europe/Moscow", label: "Moscu" },
  { value: "Asia/Tokyo", label: "Tokio" },
  { value: "Asia/Shanghai", label: "Shanghai" },
  { value: "Asia/Hong_Kong", label: "Hong Kong" },
  { value: "Asia/Singapore", label: "Singapur" },
  { value: "Asia/Dubai", label: "Dubai" },
  { value: "Asia/Kolkata", label: "Mumbai" },
  { value: "Australia/Sydney", label: "Sydney" },
  { value: "Australia/Melbourne", label: "Melbourne" },
  { value: "Pacific/Auckland", label: "Auckland" },
  { value: "Africa/Johannesburg", label: "Johannesburgo" },
  { value: "Africa/Cairo", label: "El Cairo" },
  { value: "Africa/Lagos", label: "Lagos" },
];
