export interface TimezoneOption {
  value: string;
  label: string;
}

export const timezones: TimezoneOption[] = [
  { value: "Europe/Berlin", label: "Alemania - Berlín" },
  { value: "America/Argentina/Buenos_Aires", label: "Argentina - Buenos Aires" },
  { value: "Australia/Melbourne", label: "Australia - Melbourne" },
  { value: "Europe/Vienna", label: "Austria - Viena" },
  { value: "Europe/Brussels", label: "Bélgica - Bruselas" },
  { value: "America/La_Paz", label: "Bolivia - La Paz" },
  { value: "America/Sao_Paulo", label: "Brasil - São Paulo" },
  { value: "America/Montreal", label: "Canadá - Montreal" },
  { value: "America/Toronto", label: "Canadá - Toronto" },
  { value: "America/Vancouver", label: "Canadá - Vancouver" },
  { value: "America/Santiago", label: "Chile - Santiago" },
  { value: "Asia/Hong_Kong", label: "China - Hong Kong" },
  { value: "Asia/Shanghai", label: "China - Shanghái" },
  { value: "America/Bogota", label: "Colombia - Bogotá" },
  { value: "America/San_Jose", label: "Costa Rica - San José" },
  { value: "America/Havana", label: "Cuba - La Habana" },
  { value: "Europe/Copenhagen", label: "Dinamarca - Copenhague" },
  { value: "America/Guayaquil", label: "Ecuador - Guayaquil" },
  { value: "Africa/Cairo", label: "Egipto - El Cairo" },
  { value: "America/El_Salvador", label: "El Salvador - San Salvador" },
  { value: "Asia/Dubai", label: "Emiratos Árabes - Dubái" },
  { value: "Europe/Madrid", label: "España - Madrid" },
  { value: "America/Honolulu", label: "Estados Unidos - Honolulu" },
  { value: "America/Los_Angeles", label: "Estados Unidos - Los Ángeles" },
  { value: "America/Chicago", label: "Estados Unidos - Chicago" },
  { value: "America/Denver", label: "Estados Unidos - Denver" },
  { value: "America/New_York", label: "Estados Unidos - Nueva York" },
  { value: "America/Phoenix", label: "Estados Unidos - Phoenix" },
  { value: "Europe/Helsinki", label: "Finlandia - Helsinki" },
  { value: "Europe/Paris", label: "Francia - París" },
  { value: "Europe/Athens", label: "Grecia - Atenas" },
  { value: "America/Guatemala", label: "Guatemala - Ciudad de Guatemala" },
  { value: "America/Tegucigalpa", label: "Honduras - Tegucigalpa" },
  { value: "Asia/Kolkata", label: "India - Bombay" },
  { value: "Europe/Dublin", label: "Irlanda - Dublín" },
  { value: "Asia/Tokyo", label: "Japón - Tokio" },
  { value: "America/Mexico_City", label: "México - Ciudad de México" },
  { value: "America/Managua", label: "Nicaragua - Managua" },
  { value: "Africa/Lagos", label: "Nigeria - Lagos" },
  { value: "Europe/Oslo", label: "Noruega - Oslo" },
  { value: "Pacific/Auckland", label: "Nueva Zelanda - Auckland" },
  { value: "Europe/Amsterdam", label: "Países Bajos - Ámsterdam" },
  { value: "America/Panama", label: "Panamá - Ciudad de Panamá" },
  { value: "America/Asuncion", label: "Paraguay - Asunción" },
  { value: "America/Lima", label: "Perú - Lima" },
  { value: "Europe/Warsaw", label: "Polonia - Varsovia" },
  { value: "Europe/Lisbon", label: "Portugal - Lisboa" },
  { value: "America/San_Juan", label: "Puerto Rico - San Juan" },
  { value: "Europe/London", label: "Reino Unido - Londres" },
  { value: "Europe/Prague", label: "República Checa - Praga" },
  { value: "America/Santo_Domingo", label: "República Dominicana - Santo Domingo" },
  { value: "Europe/Moscow", label: "Rusia - Moscú" },
  { value: "Asia/Singapore", label: "Singapur - Singapur" },
  { value: "Africa/Johannesburg", label: "Sudáfrica - Johannesburgo" },
  { value: "Europe/Stockholm", label: "Suecia - Estocolmo" },
  { value: "Europe/Zurich", label: "Suiza - Zúrich" },
  { value: "America/Montevideo", label: "Uruguay - Montevideo" },
  { value: "America/Caracas", label: "Venezuela - Caracas" },
];
