export const APPOINTMENT_STATUS = {
  SCHEDULED: "scheduled",
  CONFIRMED: "confirmed",
  IN_PROGRESS: "in_progress",
  COMPLETED: "completed",
  CANCELLED: "cancelled",
  NO_SHOW: "no_show",
} as const;

export type AppointmentStatus =
  (typeof APPOINTMENT_STATUS)[keyof typeof APPOINTMENT_STATUS];

export const APPOINTMENT_STATUS_LABELS: Record<AppointmentStatus, string> = {
  [APPOINTMENT_STATUS.SCHEDULED]: "Programada",
  [APPOINTMENT_STATUS.CONFIRMED]: "Confirmada",
  [APPOINTMENT_STATUS.IN_PROGRESS]: "En progreso",
  [APPOINTMENT_STATUS.COMPLETED]: "Completada",
  [APPOINTMENT_STATUS.CANCELLED]: "Cancelada",
  [APPOINTMENT_STATUS.NO_SHOW]: "No se presentó",
};

export const APPOINTMENT_STATUS_OPTIONS = [
  { value: APPOINTMENT_STATUS.SCHEDULED, label: APPOINTMENT_STATUS_LABELS[APPOINTMENT_STATUS.SCHEDULED] },
  { value: APPOINTMENT_STATUS.CONFIRMED, label: APPOINTMENT_STATUS_LABELS[APPOINTMENT_STATUS.CONFIRMED] },
  { value: APPOINTMENT_STATUS.IN_PROGRESS, label: APPOINTMENT_STATUS_LABELS[APPOINTMENT_STATUS.IN_PROGRESS] },
  { value: APPOINTMENT_STATUS.COMPLETED, label: APPOINTMENT_STATUS_LABELS[APPOINTMENT_STATUS.COMPLETED] },
  { value: APPOINTMENT_STATUS.CANCELLED, label: APPOINTMENT_STATUS_LABELS[APPOINTMENT_STATUS.CANCELLED] },
  { value: APPOINTMENT_STATUS.NO_SHOW, label: APPOINTMENT_STATUS_LABELS[APPOINTMENT_STATUS.NO_SHOW] },
] as const;

